#include "gate_model_api.h"
#include "mlp_model_data.h"
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "esp_log.h"

static const char* TAG = "MLP";

namespace {
    // 12 KB is comfortably larger than the arena actually needed by this model
    // (~4 KB of activations + ~4 KB of TFLite Micro overhead).  If AllocateTensors
    // reports failure, increase this value.
    constexpr int kTensorArenaSize = 12 * 1024;
    alignas(16) uint8_t tensor_arena[kTensorArenaSize];

    const tflite::Model* s_model = nullptr;
    tflite::MicroInterpreter* s_interpreter = nullptr;
    bool s_initialized = false;
}

static void mlp_init() {
    s_model = tflite::GetModel(mlp_model_tflite);
    if (s_model->version() != TFLITE_SCHEMA_VERSION) {
        ESP_LOGE(TAG, "Schema version mismatch (expected %d, got %u) — rebuild mlp_model_data.h",
                 TFLITE_SCHEMA_VERSION, (unsigned)s_model->version());
        return;
    }

    // AllOpsResolver includes every built-in op.  For a tighter binary, replace it
    // with MicroMutableOpResolver listing only FULLY_CONNECTED, RELU, LOGISTIC,
    // SUB, and MUL (the ops generated by the Normalization + Dense layers).
    static tflite::AllOpsResolver resolver;
    static tflite::MicroInterpreter static_interpreter(
        s_model, resolver, tensor_arena, kTensorArenaSize);
    s_interpreter = &static_interpreter;

    if (s_interpreter->AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "AllocateTensors failed — increase kTensorArenaSize");
        s_interpreter = nullptr;
        return;
    }

    ESP_LOGI(TAG, "MLP ready. Arena used: %u / %u bytes",
             (unsigned)s_interpreter->arena_used_bytes(), (unsigned)kTensorArenaSize);
    s_initialized = true;
}

// Matches the fill_feature_vector layout used by gate_model.cpp:
//   features[0]      = distance
//   features[1..14]  = v[0]..v[13]   (earliest → most recent)
//   features[15..27] = a[0]..a[12]   (earliest → most recent)
//
// mlp.py reverses the CSV column order when building the training set so that
// this ordering is consistent between training and inference.
extern "C" bool predict_gate_action_mlp(float distance, float* v, float* a) {
    if (!s_initialized) {
        mlp_init();
    }
    if (!s_initialized || s_interpreter == nullptr) {
        ESP_LOGE(TAG, "MLP not ready — failsafe CLOSE");
        return true;
    }

    TfLiteTensor* input = s_interpreter->input(0);
    input->data.f[0] = distance;
    for (int i = 0; i < 14; i++) input->data.f[1 + i] = v[i];
    for (int i = 0; i < 13; i++) input->data.f[15 + i] = a[i];

    if (s_interpreter->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG, "Invoke failed — failsafe CLOSE");
        return true;
    }

    TfLiteTensor* output = s_interpreter->output(0);
    float confidence = output->data.f[0];
    ESP_LOGI(TAG, "confidence=%.4f -> %s", confidence, confidence >= 0.5f ? "CLOSE" : "OPEN");
    return confidence >= 0.5f;
}
